### PR TITLE
Add username transformer and form type for invitations

### PR DESCRIPTION
**Pull request by Problematic**
There are a couple things here. The solution I'm using here requires the bundle to be configured know about the concrete user class, which I'm not too fond of, but it's the only thing I could think of that disconnects the user selection process from Doctrine ORM (using the `entity` form type, for example). If we can come up with another way that works more smoothly, I'd be happy to write the code, but for now, this should work.

### CODE REVIEW

**Comment by Problematic** [comment]
Actually, one thing that would make me feel (a little) better about this is making the username transformation optional.

**Comment by robzienert** [comment]
This solution will be fine for now. Down the road I'd like to see this either be a select, or add an autocomplete frontend for using this current text field.

**Comment by Problematic** [comment]
I agree; though if we go with a select, there will have to be some sort of sensible filtering, so that busy and/or popular sites don't have gargantuan dropdowns to run through.

**Comment by robzienert** [comment]
Absolutely, which is why I'm a little more bias to an autocomplete text field for that reason. Perhaps when we get to revisiting this, we can explore providing different OTB strategies that devs can swap out. /pie-in-the-sky

**Pull request merged**
