### PR TITLE
Merge body of work from LimeCalendarBundle [wip]

### PR DESCRIPTION
**Pull request by Problematic**
This PR is for merging work done on the LimeCalendarBundle into this bundle to consolidate community effort. The merge is very much a work in progress, so please feel free to comment and tear it apart at will. I'll defend my design choices as best I can, and hopefully we can come up with something better than before.

### CODE REVIEW

**Comment by robzienert** [comment]
Please add `public` declarations to functions, as opposed to simply `function`. Aside from that, it's looking pretty good.

**Comment by Problematic** [comment]
In interfaces? I left them out because interface methods are implicitly public, but I'll add it in if you'd like.

**Comment by Problematic** [comment]
Oh, I see where you're talking about. Huh. Must've been working quickly.

**Comment by iampersistent** [comment]
When do you anticipate this getting pulled? I've started some of the same work, but I'll stop and just focus on the ODM aspect of it.

**Comment by Problematic** [comment]
I'm pushing out complete chunks in my commits (less some bug fixes from hasty coding), so it can be merged anytime, really. @robzienert did you have a marker you wanted me to hit before merge? If not, maybe we can get the current code reviewed and merged so others can start working from it.

**Comment by robzienert** [comment]
I will merge this in now. From our previous conversations, I knew you were going to have a rolling pull request, so I was just letting you go at it.

**Pull request merged**
